### ISSUE TITLE
[Feature Requests] Additional control inputs, recents bar options, auto-hide filter icons when empty, VNEI tab renaming 

### ISSUE THREAD

**Issue by Abbanon** [MSchmoecker/VNEI#11]
It would be very nice if the following features were to be implemented into VNEI. Would you kindly consider them?
- **Input to remove items from the "recents" bar**
_This could, for example, be mapped to the mousewheel (Mouse 3) click and done when moused over the desired item to remove._

- **Input to "go back" to the item list from a selected item, without needing to click the `X`**
_This could, for example, be mapped to mouse right-click (Mouse 2) and done anywhere within VNEI's window area._

- **Add a clearer divider line between "recents" bar and the item list**
_I myself, and maybe some other users, get distracted by the "recents" bar and think it's the topmost row of the actual item list at first glance. This is because it's packed so closely to the item list itself, with only a paltry amount of space existing between the two. Having a visible, improved spacer/divider line between them would assist greatly here._

- **The option to disable/hide the "recents" bar completely**
_This one's pretty self-explanatory._

- **Auto-hide individual filter icons when no data is found in them**
_I've used the custom blacklist to hide every creature and undefined item. It would be great if those filter icons were to be hidden when no data is found, maybe with an option._

- **The option to rename/change the text of the VNEI tab, when "Attach to Crafting" is true/enabled**
_Having a tab named "VNEI" when you have the `Attach to Crafting` option enabled doesn't exactly fit the Valheim style. It would be nice to allow user customization for the text in this tab field, let's say for instance I wanted it the tab to read "LIBRARY" or "GUIDE" instead._

**Comment by MSchmoecker** [comment]
Thanks for the suggestions and the explanations.

> * Input to remove items from the "recents" bar
> * The option to disable/hide the "recents" bar completely
> * Auto-hide individual filter icons when no data is found in them,
> * The option to rename/change the text of the VNEI tab, when "Attach to Crafting" is true/enabled

yes this can be added, those are mostly small changes and I see the benefit to have those features

> * Input to "go back" to the item list from a selected item, without needing to click the X

not entirely sure if this is a good idea, since it may be pressed by accident and it's not clear what happens. But I get that a faster way to navigate is desirable, have to test some solutions

> * Add a clearer divider line between "recents" bar and the item list

this is a tough one. It's not really possible to increase the space without removing a row of the actual items and I'm not sure if a divider would fit with the style either. In my opinion, enough space to be told apart but yeah at first glance it may be confusing

**Comment by MSchmoecker** [comment]
Alright, as always it took longer then expected. But now most of the QoL features are implented, the most noteworthy change is to the "go back"-feature. Instead of clicking in the UI to go to the search, the whole history can be navigated.

Feel free to give feedback, a test version can be download here if you want to [VNEI.zip](https://github.com/MSchmoecker/VNEI/files/10203484/VNEI.zip). If you use Discord, you may want to join the [Jötunn Discord](https://discord.gg/DdUt6g7gyA) and we can discuss the features there.

Also, there are some open bugs with Auga that I will most likely resolve before this will be released.

This is the current changelog:
- Added config option to set the mouse button for item cheating
- Added the option to remove items from the last viewed list by middle clicking. The mouse button can be changed in the config
- Added a config option to disable the last viewed list
- Added a config option to rename the attached tab
- Added a visual separation between the last viewed list and the item view
- Added item count on filter button hover and disable filter with zero items
- Added a history of the last viewed pages between search and recipes. The default hotkeys to navigate the history are `PageUp` and `PageDown`

**Comment by MSchmoecker** [comment]
This is now released with VNEI 0.8.0 :)
