### ISSUE TITLE
Request - server utility and player assistance

### ISSUE THREAD

**Issue by Oosquai** [MSchmoecker/VNEI#18]
Hi!  I've been running a dedicated server for a dozen or so friends for several weeks, and we're having a blast.  I use VNEI extensively as an admin to answer questions as we play together, and of course I have Show Only Known = False so I can look up stuff ahead of my own character's progress to help answer their questions as admin.  I get LOTS of feedback about how much everyone playing wishes they could easily look up materials to recipes and such...  which of course I can do with VNEI.  I haven't distributed it to them though, because it's only client-side and I can't prevent them from spoiling all the end-game gear they've yet to discover.
I know it's probably a lot of work, and I totally understand if this isn't something you want to do, but I thought I'd ask...  would you ever consider adding server-sync?  And also a config setting like Admin Show Only Known?
Regardless, I love your mods.  Thank you so much!

**Comment by Oosquai** [comment]
Just wanted to clarify, I'm hoping for Server-Sync for the following settings:
Enable Cheating
Enable Spawning Creatures
Use Item Blacklist (assuming server-side .blacklist file gets used)
Show Only Known
Admin Show Only Known (if you desire to add this.  if not, I'd still love server-sync for all the others, if you're so inclined!)

Thanks so much!  This mod rocks!

**Comment by MSchmoecker** [comment]
Hi, thank for enjoying the mod!

The cheat options are not syncing because only admin can cheat, regardless of what the cheat setting is set to.

The item blacklist and ShowOnlyKnown are not syncing because of a design choice, not because it would be hard to add.
The reason is, there isn't really any benefit to force this for all players. Some might enjoy not having everything visible and to discover recipes but not everyone.   Looking recipes up isn't something that can entirely be locked away. For example, a player might start a single player world and looks up what the mods add.

Therefore, having it as a client side setting lets every player choose what fits his playstlye best.
You can still distribute a default config in the mod pack, where the settings is turned on by default.

**Comment by Oosquai** [comment]
Hi!  That all makes sense.  Thanks for the reply and for the awesome mods you maintain!
